# AdaptDiffuser Configuration

# Hardware settings
device: "auto"  # "auto", "cuda", "cpu"
precision: "float32"  # "float32", "float16", "bfloat16"

# Model settings
model:
  img_size: 32  # Size of trajectory representation
  channels: 3   # Number of channels in trajectory representation
  model_channels: 128
  channel_mult: [1, 2, 4, 8]
  attention_resolutions: [16, 8]
  num_res_blocks: 2
  dropout: 0.1
  use_scale_shift_norm: true
  resblock_updown: true
  num_heads: 4
  num_head_channels: 64
  use_checkpoint: true  # Use gradient checkpointing to save memory

# Diffusion settings
guidance_scale: 3.0  # Scale for reward guidance (higher = stronger guidance)
use_ddim: true       # Use DDIM sampling (faster but potentially less diverse)
sampling_steps: 50   # Number of denoising steps

# Noise scheduler settings
noise_scheduler:
  type: "cosine"  # "linear", "cosine", "quadratic"
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  s: 0.008  # For cosine scheduler only

# Buffer settings
buffer_capacity: 10000  # Maximum number of trajectories to store
prioritized_replay: true  # Use prioritized experience replay

# Adaptation settings
adaptation_rate: 1.0e-5  # Learning rate for adaptation
adaptation_steps: 10    # Number of gradient steps per adaptation iteration
quality_threshold: 0.7  # Minimum reward threshold for high-quality samples

# Task embedding settings
task_embedding:
  embedding_dim: 64
  embedding_model: "default"  # "default", "sentence_transformer", "clip"
  cache_capacity: 1000

# Multi-task settings
multi_task: false  # Enable multi-task support
task_similarity_threshold: 0.7  # Threshold for task transfer

# Self-improvement settings
self_improvement:
  iterations: 3
  trajectories_per_iter: 50
  quality_threshold: 0.7
  synthetic_expert_ratio: 0.5

# Discriminator settings
discriminator:
  hidden_dim: 128
  n_layers: 3
  dropout: 0.1

# Synthetic expert settings
synthetic_expert:
  guidance_scale: 5.0
  sampling_steps: 100
  use_ddim: true
  diversity_penalty: 0.1

# Checkpoint settings
checkpoint_dir: "./checkpoints/adaptdiffuser"
save_frequency: 5  # Save every N adaptation iterations

# Logging settings
logging:
  level: "INFO"  # "DEBUG", "INFO", "WARNING", "ERROR"
  log_to_file: false
  log_file: "adaptdiffuser.log"
  log_metrics: true

# Advanced settings
advanced:
  adaptive_guidance: true  # Gradually change guidance throughout denoising
  guidance_min_step_percent: 0.1
  guidance_max_step_percent: 0.9
  ema_rate: 0.999  # Exponential moving average rate for model weights
  selection_strategy: "hybrid"  # "topk", "temperature", "diversity", "hybrid"